### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by jamisonvalentine** [cloud0x9/Schedule-Creator#28]
Don't know where else to put this besides a plain email but I'll delete when the question is clear.

My question is, are we all receiving the same grade for the code review regardless of who goes up?

**Comment by xsfar** [comment]
I believe it is individual, since your only suppose to present the code that you wrote, and on the syllabus it says,"Code Reviews: 15 points (3 reviews of 5 points each)". I believe there is enough time in the semester for everyone to present 3 times, If it were a group grade the final grades given by the syllabus wouldn't add up. I maybe wrong I dont know for sure.
